version: 2
updates:
- package-ecosystem: cargo
  directory: /
  schedule:
    interval: weekly
    day: monday
    time: 06:00
    timezone: Etc/UTC
  open-pull-requests-limit: 5
  groups:
    rust-updates:
      patterns:
      - '*'
- package-ecosystem: npm
  directory: /
  schedule:
    interval: weekly
    day: monday
    time: 06:00
    timezone: Etc/UTC
  open-pull-requests-limit: 5
  groups:
    javascript-updates:
      patterns:
      - '*'
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
    day: monday
    time: 06:00
    timezone: Etc/UTC
  open-pull-requests-limit: 5
  groups:
    action-updates:
      patterns:
      - '*'
