[package]
name = "nft-factory"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib"]
doctest = false

[dependencies]
soroban-sdk.workspace = true
factory-common = { path = "../factory-common" }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
